name: nowje-spring-xml-to-code-runner

on:
  push:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'adopt'
          cache: maven

      - name: Build and Test
        run:  mvn clean install

      - name: Coverage Reports
        run: mvn clean jacoco:prepare-agent install package jacoco:report omni-coveragereporter:report
        env:
           COVERALLS_REPO_TOKEN: ${{ secrets.COVERALLS_REPO_TOKEN }}
           CODACY_PROJECT_TOKEN: ${{ secrets.CODACY_PROJECT_TOKEN }}
           CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
